"""Bring a scan annotated in 3D Slicer into the web editor as a new case.

    python ml/scripts/import_slicer.py <base> <CASE_ID> <volume.nrrd> <segmentation.seg.nrrd> \
        [--map Segment_1=bme] [--class bme] [--dry-run]

Writes
    data/nifti/<CASE>/<CASE>_primary.nii.gz      the scan, from the Slicer volume
    data/annotations/<CASE>/<CASE>.seg.nrrd      the segmentation, segments renamed
    data/worklist.csv                            one new row, so the case is listed

CASE_ID must be a pseudonymous ID (BME-123 / NBME-123) not already in use; the
source files keep their original names and never enter data/ under them.

`--map` renames segments whose names seg2nifti.py does not recognise, the same
way rename_segments.py does. Only the person who drew a segment knows what it
holds, so the mapping is never guessed: an unrecognised name without a --map is
refused.

Nothing that exists is overwritten. import_slicer_all.py does a whole Drive
export at once through import_case().
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path

import nibabel as nib
import nrrd
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from rename_segments import VALID, segments_in  # noqa: E402
from seg2nifti import canonical, seg_affine_ras  # noqa: E402

ID = re.compile(r"^(BME|NBME)-\d{3}$")
PLANES = ("sagittal", "coronal", "axial")


def import_case(base: Path, cid: str, volume: Path, segmentation: Path,
                renames: dict[str, str], cls: str, fields: list[str],
                dry_run: bool = False) -> dict:
    """Write one case's scan and segmentation; return its worklist row.

    Raises ValueError, before writing anything, if the case cannot be imported.
    """
    if not ID.match(cid):
        raise ValueError(f"{cid!r} is not a pseudonymous case ID like BME-123")
    vol_out = base / "data" / "nifti" / cid / f"{cid}_primary.nii.gz"
    seg_out = base / "data" / "annotations" / cid / f"{cid}.seg.nrrd"
    for p in (vol_out, seg_out):
        if p.exists():
            raise ValueError(f"{p} already exists - pick another case ID")

    # --- scan
    vdata, vhdr = nrrd.read(str(volume))
    if vdata.ndim != 3:
        raise ValueError(f"expected a 3D volume, got shape {vdata.shape}")
    affine = seg_affine_ras(vhdr)
    spacing = np.linalg.norm(affine[:3, :3], axis=0)
    plane = PLANES[int(np.argmax(np.abs(affine[:3, 2])))]

    # --- segmentation
    sdata, shdr = nrrd.read(str(segmentation))
    segs = segments_in(shdr)
    if not segs:
        raise ValueError("no segment metadata - is this really a .seg.nrrd?")
    for old, new in renames.items():
        if new not in VALID:
            raise ValueError(f"{new!r} is not a valid name. Use one of: {', '.join(VALID)}")
        if old not in segs:
            raise ValueError(f"no segment named {old!r}. Present: {', '.join(segs)}")
    final = [renames.get(n, n) for n in segs]
    unknown = [n for n, f in zip(segs, final) if canonical(f) is None]
    if unknown:
        raise ValueError(f"unrecognised segment name(s) {unknown}. Say what each holds, "
                         f"e.g. --map {unknown[0]}=bme")
    if len({canonical(f) for f in final}) != len(final):
        raise ValueError(f"two segments would share a name: {final}")

    print(f"{cid}  scan {vdata.shape} {plane}, spacing {np.round(spacing, 3).tolist()} mm; "
          + ", ".join(f"{o!r}" + (f" -> {n!r}" if n != o else "") for o, n in zip(segs, final)))

    row = {k: "" for k in fields}
    row.update({
        "case_id": cid,
        "class": cls,
        "plane": plane,
        "n_slices": str(vdata.shape[2]),
        "slice_thickness": f"{spacing[2]:.4f}",
        "isotropic": str(bool(spacing.max() / spacing.min() < 2)),
        "nifti": f"data/nifti/{cid}/{cid}_primary.nii.gz",
        "status": "ok",
        "assigned_to": "ALL",
        "is_overlap": "False",
    })
    if dry_run:
        return row

    for old, new in renames.items():
        shdr[segs[old]["key"]] = new
        auto = f"{segs[old]['index']}_NameAutoGenerated"
        if auto in shdr:
            shdr[auto] = "0"
    vol_out.parent.mkdir(parents=True, exist_ok=True)
    seg_out.parent.mkdir(parents=True, exist_ok=True)
    nib.save(nib.Nifti1Image(vdata, affine), str(vol_out))
    nrrd.write(str(seg_out), sdata, shdr)
    return row


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("base")
    ap.add_argument("case_id")
    ap.add_argument("volume")
    ap.add_argument("segmentation")
    ap.add_argument("--map", action="append", default=[], metavar="OLD=NEW")
    ap.add_argument("--class", dest="cls", choices=("bme", "non_bme"), default="bme")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    base, cid = Path(args.base), args.case_id
    worklist = base / "data" / "worklist.csv"
    if not worklist.exists():
        sys.exit(f"missing {worklist}")
    with worklist.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        fields = reader.fieldnames or []
        if any(r.get("case_id") == cid for r in reader):
            sys.exit(f"{cid} is already in {worklist.name} - pick another case ID")

    renames = {}
    for item in args.map:
        old, _, new = item.partition("=")
        renames[old] = new
    try:
        row = import_case(base, cid, Path(args.volume), Path(args.segmentation),
                          renames, args.cls, fields, args.dry_run)
    except ValueError as e:
        sys.exit(str(e))
    if args.dry_run:
        print("\ndry run: nothing written")
        return
    with worklist.open("a", newline="", encoding="utf-8") as f:
        csv.DictWriter(f, fieldnames=fields).writerow(row)
    print("\nwritten. Open the case in the 3D tab.")


if __name__ == "__main__":
    main()
