"""Rename segments inside a .seg.nrrd that was saved with Slicer's default names.

    # see what is in the file
    python ml/scripts/rename_segments.py <file.seg.nrrd>

    # rename explicitly
    python ml/scripts/rename_segments.py <file.seg.nrrd> \
        --map Segment_1=bone_marrow --map Segment_2=bme

Only for annotations already saved with auto-generated names like `Segment_1`.
New sessions should use ml/scripts/slicer_setup.py, which names them correctly
from the start.

The mapping is never inferred. `Segment_1` carries no information about which
structure it holds — only the person who drew it knows. Guessing here would
mislabel anatomy silently, which is worse than refusing. So you state the
mapping and this applies it.

Writes in place after saving a `.bak` copy.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

try:
    import nrrd
    import numpy as np
except ImportError:
    sys.exit("pynrrd/numpy missing.  pip install pynrrd numpy")

VALID = ("bone_marrow", "bme", "uncertain")


def segments_in(header) -> dict[str, dict]:
    out = {}
    for key, value in header.items():
        if key.startswith("Segment") and key.endswith("_Name"):
            idx = key.split("_")[0]
            out[str(value)] = {
                "key": key,
                "index": idx,
                "label": header.get(f"{idx}_LabelValue"),
                "layer": header.get(f"{idx}_Layer", 0),
            }
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("path")
    ap.add_argument("--map", action="append", default=[],
                    metavar="OLD=NEW", help="e.g. --map Segment_1=bone_marrow")
    ap.add_argument("--no-backup", action="store_true")
    args = ap.parse_args()

    path = Path(args.path)
    if not path.exists():
        sys.exit(f"no such file: {path}")

    data, header = nrrd.read(str(path))
    segs = segments_in(header)

    print(f"{path.name}")
    print(f"  array {data.shape} {data.dtype}\n")
    print("  segments present:")
    for name, info in segs.items():
        lv = info["label"]
        try:
            layer = data[int(info["layer"])] if data.ndim == 4 else data
            n = int((layer == int(lv)).sum()) if lv is not None else -1
        except Exception:
            n = -1
        flag = "" if name in VALID else "   <- not a name seg2nifti accepts"
        print(f"    {name!r:24s} label={lv} voxels={n}{flag}")

    if not args.map:
        unknown = [n for n in segs if n not in VALID]
        if unknown:
            print("\n  These will be rejected by seg2nifti.py. Rename them, e.g.:")
            for n in unknown:
                print(f"    --map {n}=bone_marrow")
            print(f"\n  Valid targets: {', '.join(VALID)}")
        else:
            print("\n  All segment names are already valid.")
        return

    pairs = []
    for item in args.map:
        if "=" not in item:
            sys.exit(f"bad --map {item!r}, expected OLD=NEW")
        old, new = item.split("=", 1)
        if new not in VALID:
            sys.exit(f"{new!r} is not a valid target. Use one of: {', '.join(VALID)}")
        if old not in segs:
            sys.exit(f"no segment named {old!r} in this file")
        pairs.append((old, new))

    targets = [n for _, n in pairs]
    if len(set(targets)) != len(targets):
        sys.exit("two segments cannot map to the same name")

    if not args.no_backup:
        bak = path.with_suffix(path.suffix + ".bak")
        shutil.copy2(path, bak)
        print(f"\n  backup -> {bak.name}")

    for old, new in pairs:
        header[segs[old]["key"]] = new
        auto = f"{segs[old]['index']}_NameAutoGenerated"
        if auto in header:
            header[auto] = "0"
        print(f"  {old!r} -> {new!r}")

    nrrd.write(str(path), data, header)
    print(f"\n  written. now run:  python ml/scripts/seg2nifti.py <base>")


if __name__ == "__main__":
    main()
