"""Write a Slicer-compatible .seg.nrrd from a raw labelmap produced by the web editor.

    python ml/scripts/write_seg.py <base> <CASE_ID> <raw_file>

`raw_file` is a flat uint8 buffer, one byte per voxel, in the SAME index order as
the case's `_primary.nii.gz` (x fastest). Values: 0 background, 1 bone_marrow,
2 bme, 3 uncertain.

Geometry is copied from the source volume and converted RAS -> LPS, which is the
inverse of the transform in seg2nifti.py. That direction was verified against a
real Slicer export: the affine it produces matches Slicer's own embedded
"Reference image geometry" matrix exactly. Keep the two in step — if one changes
the other must change with it, or annotations will silently shift.

Called by the web editor's save endpoint. Safe to run by hand.
"""

from __future__ import annotations

import sys
from pathlib import Path

import nibabel as nib
import numpy as np
import nrrd

SEGMENTS = [
    ("bone_marrow", 1, (0.86, 0.82, 0.71)),
    ("bme", 2, (0.95, 0.30, 0.22)),
    ("uncertain", 3, (0.55, 0.55, 0.60)),
]


def main():
    if len(sys.argv) < 4:
        sys.exit(__doc__)
    base, case_id, raw_path = Path(sys.argv[1]), sys.argv[2], Path(sys.argv[3])
    annotator = sys.argv[4] if len(sys.argv) > 4 else ""

    vol_path = base / "data" / "nifti" / case_id / f"{case_id}_primary.nii.gz"
    if not vol_path.exists():
        sys.exit(f"no volume: {vol_path}")

    img = nib.load(str(vol_path))
    shape = img.shape

    raw = np.fromfile(raw_path, dtype=np.uint8)
    if raw.size != int(np.prod(shape)):
        sys.exit(f"size mismatch: got {raw.size} voxels, volume is {shape} = {int(np.prod(shape))}")
    lab = raw.reshape(shape, order="F")

    present = {v: int((lab == v).sum()) for _, v, _ in SEGMENTS}
    if not any(present.values()):
        sys.exit("labelmap is empty — nothing painted")

    # RAS (NIfTI) -> LPS (NRRD): negate the x and y components of every axis
    # vector and of the origin. Inverse of seg2nifti.py.
    aff = img.affine
    directions = np.array([aff[:3, 0], aff[:3, 1], aff[:3, 2]])
    directions[:, 0] *= -1
    directions[:, 1] *= -1
    origin = aff[:3, 3].astype(float).copy()
    origin[0] *= -1
    origin[1] *= -1

    header = {
        "space": "left-posterior-superior",
        "space directions": directions,
        "space origin": origin,
        "kinds": ["domain", "domain", "domain"],
        "Segmentation_MasterRepresentation": "Binary labelmap",
        "Segmentation_ContainedRepresentationNames": "Binary labelmap|",
        "Segmentation_ReferenceImageExtentOffset": "0 0 0",
    }
    for i, (name, value, rgb) in enumerate(SEGMENTS):
        header[f"Segment{i}_Name"] = name
        header[f"Segment{i}_ID"] = f"Segment_{value}"
        header[f"Segment{i}_LabelValue"] = str(value)
        header[f"Segment{i}_Layer"] = "0"
        header[f"Segment{i}_Color"] = " ".join(f"{c:.6f}" for c in rgb)
        header[f"Segment{i}_NameAutoGenerated"] = "0"
        header[f"Segment{i}_Extent"] = f"0 {shape[0]-1} 0 {shape[1]-1} 0 {shape[2]-1}"

    out_dir = base / "data" / "annotations" / case_id
    out_dir.mkdir(parents=True, exist_ok=True)

    # Two files, deliberately.
    #
    #   <CASE>.seg.nrrd            canonical — the one the training pipeline reads
    #   <CASE>__<annotator>.seg.nrrd   this person's own copy, kept forever
    #
    # Several people annotate the same case on purpose: the overlap set exists so
    # inter-rater Dice can be measured, and that number is the model's realistic
    # ceiling. If everyone wrote only to the canonical name, the second person to
    # save would erase the first, and the comparison would be impossible. Keeping
    # a per-annotator copy costs ~10 KB and preserves it.
    written = []
    if annotator:
        safe = "".join(c if (c.isalnum() or c in "-_") else "_" for c in annotator)[:40]
        per = out_dir / f"{case_id}__{safe}.seg.nrrd"
        nrrd.write(str(per), lab, header)
        written.append(per)

    out = out_dir / f"{case_id}.seg.nrrd"
    nrrd.write(str(out), lab, header)
    written.append(out)

    counts = "  ".join(f"{n}={present[v]}" for n, v, _ in SEGMENTS if present[v])
    for w in written:
        print(f"wrote {w}")
    print(f"  {counts}")


if __name__ == "__main__":
    main()
